server:
  port: 8501

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOSTNAME:localhost}:8761/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.chiwooplatform.cloud.sample: DEBUG
  file: logs/cluster-api.log
  path: ./logs/
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"