server:
  port: 8501

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOSTNAME:localhost}:8761/eureka/

logging:
  level:
    org.chiwooplatform.cloud.sample.proxy: DEBUG
    org.chiwooplatform.cloud.sample: DEBUG
